name: paccmann_gp
channels:
  - https://conda.anaconda.org/rdkit
  - conda-forge
dependencies:
  - scikit-optimize=0.8.1
  - loguru=0.5.3
  - python=3.7
  - pip>=19.1,<20.3
  - pip:
    - -r file:requirements.txt
    # development
    - -r file:dev_requirements.txt
    - -e .
